---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: rucio-db
    literals:
      - password=secret

configMapGenerator:
  - name: rucio-db-hostname
    literals:
      - RUCIO_DB=rucio-db.pic.es
  - name: rucio-db-dump
    literals:
      - RUCIO_DB_DUMP=/rucio-pic/rucio-backups/rucio-db.dump

resources:
  - service.yaml
  - deployment.yaml
  - cronjob.yaml
