---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucio-postgresql
  labels:
    app: postgres
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        tier: data
    spec:
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: psql-test

      containers:
      - name: postgres
        image: postgres:13.3
        imagePullPolicy: IfNotPresent
        args: 
        - postgres
        - -p 5432
        - -c
        - max_connections=1000
        - -c
        - shared_buffers=1024MB 

        volumeMounts:
        - name: postgresdb
          mountPath: /mnt/postgresql/pgdata
          
        env:
        - name: POSTGRES_DB
          value: rucio
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: POSTGRES_USER
          value: rucio
        - name: POSTGRES_PASSWORD
          value: secret
        - name: RUCIO_DB_DUMP
          value: /rucio/rucio-db.dump

        ports:
        - containerPort: 5432 
---
apiVersion: v1
kind: Service
metadata:
  name: rucio-postgresql
spec:
  type: ClusterIP
  # type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432


